// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'api/matrix.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1400931781;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_synnal',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiMatrixMatrixServiceClearRooms({
    required MatrixService that,
  });

  Future<MatrixService> crateApiMatrixMatrixServiceCreate({
    required String homeserver,
    required String storePath,
    required String storePassphrase,
  });

  Future<MatrixRoomSummary> crateApiMatrixMatrixServiceCreatePrivateRoom({
    required MatrixService that,
    required String name,
    required List<String> invitedUserIds,
  });

  Future<void> crateApiMatrixMatrixServiceDeleteRoom({
    required MatrixService that,
    required String roomId,
  });

  Future<String?> crateApiMatrixMatrixServiceGetDisplayName({
    required MatrixService that,
  });

  Future<bool> crateApiMatrixMatrixServiceIsLoggedIn({
    required MatrixService that,
  });

  Future<MatrixRoomSummary> crateApiMatrixMatrixServiceJoinInvitedRoom({
    required MatrixService that,
    required String roomId,
  });

  Future<List<MatrixChatMessage>> crateApiMatrixMatrixServiceListMessages({
    required MatrixService that,
    required String roomId,
  });

  Future<MatrixRoomsSnapshot> crateApiMatrixMatrixServiceListRooms({
    required MatrixService that,
  });

  Future<String> crateApiMatrixMatrixServiceLogin({
    required MatrixService that,
    required String username,
    required String password,
    String? deviceId,
  });

  Future<void> crateApiMatrixMatrixServiceLogout({required MatrixService that});

  Future<String> crateApiMatrixMatrixServiceRegisterUser({
    required MatrixService that,
    required String username,
    required String password,
    required String displayName,
  });

  Future<void> crateApiMatrixMatrixServiceResetClient({
    required MatrixService that,
  });

  Future<void> crateApiMatrixMatrixServiceRestore({
    required MatrixService that,
    required String sessionJson,
  });

  Future<void> crateApiMatrixMatrixServiceSendMessage({
    required MatrixService that,
    required String roomId,
    required String body,
  });

  Stream<List<MatrixChatMessage>> crateApiMatrixMatrixServiceWatchMessages({
    required MatrixService that,
    required String roomId,
  });

  Stream<MatrixRoomsSnapshot> crateApiMatrixMatrixServiceWatchRooms({
    required MatrixService that,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MatrixService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MatrixService;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MatrixServicePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiMatrixMatrixServiceClearRooms({
    required MatrixService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceClearRoomsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceClearRoomsConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_clear_rooms",
        argNames: ["that"],
      );

  @override
  Future<MatrixService> crateApiMatrixMatrixServiceCreate({
    required String homeserver,
    required String storePath,
    required String storePassphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(homeserver, serializer);
          sse_encode_String(storePath, serializer);
          sse_encode_String(storePassphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceCreateConstMeta,
        argValues: [homeserver, storePath, storePassphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceCreateConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_create",
        argNames: ["homeserver", "storePath", "storePassphrase"],
      );

  @override
  Future<MatrixRoomSummary> crateApiMatrixMatrixServiceCreatePrivateRoom({
    required MatrixService that,
    required String name,
    required List<String> invitedUserIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          sse_encode_list_String(invitedUserIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_matrix_room_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceCreatePrivateRoomConstMeta,
        argValues: [that, name, invitedUserIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceCreatePrivateRoomConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_create_private_room",
        argNames: ["that", "name", "invitedUserIds"],
      );

  @override
  Future<void> crateApiMatrixMatrixServiceDeleteRoom({
    required MatrixService that,
    required String roomId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceDeleteRoomConstMeta,
        argValues: [that, roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceDeleteRoomConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_delete_room",
        argNames: ["that", "roomId"],
      );

  @override
  Future<String?> crateApiMatrixMatrixServiceGetDisplayName({
    required MatrixService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceGetDisplayNameConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceGetDisplayNameConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_get_display_name",
        argNames: ["that"],
      );

  @override
  Future<bool> crateApiMatrixMatrixServiceIsLoggedIn({
    required MatrixService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceIsLoggedInConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceIsLoggedInConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_is_logged_in",
        argNames: ["that"],
      );

  @override
  Future<MatrixRoomSummary> crateApiMatrixMatrixServiceJoinInvitedRoom({
    required MatrixService that,
    required String roomId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_matrix_room_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceJoinInvitedRoomConstMeta,
        argValues: [that, roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceJoinInvitedRoomConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_join_invited_room",
        argNames: ["that", "roomId"],
      );

  @override
  Future<List<MatrixChatMessage>> crateApiMatrixMatrixServiceListMessages({
    required MatrixService that,
    required String roomId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_matrix_chat_message,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceListMessagesConstMeta,
        argValues: [that, roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceListMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_list_messages",
        argNames: ["that", "roomId"],
      );

  @override
  Future<MatrixRoomsSnapshot> crateApiMatrixMatrixServiceListRooms({
    required MatrixService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_matrix_rooms_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceListRoomsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceListRoomsConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_list_rooms",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiMatrixMatrixServiceLogin({
    required MatrixService that,
    required String username,
    required String password,
    String? deviceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          sse_encode_opt_String(deviceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceLoginConstMeta,
        argValues: [that, username, password, deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceLoginConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_login",
        argNames: ["that", "username", "password", "deviceId"],
      );

  @override
  Future<void> crateApiMatrixMatrixServiceLogout({
    required MatrixService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceLogoutConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceLogoutConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_logout",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiMatrixMatrixServiceRegisterUser({
    required MatrixService that,
    required String username,
    required String password,
    required String displayName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          sse_encode_String(displayName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceRegisterUserConstMeta,
        argValues: [that, username, password, displayName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceRegisterUserConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_register_user",
        argNames: ["that", "username", "password", "displayName"],
      );

  @override
  Future<void> crateApiMatrixMatrixServiceResetClient({
    required MatrixService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceResetClientConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceResetClientConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_reset_client",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiMatrixMatrixServiceRestore({
    required MatrixService that,
    required String sessionJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          sse_encode_String(sessionJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceRestoreConstMeta,
        argValues: [that, sessionJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceRestoreConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_restore",
        argNames: ["that", "sessionJson"],
      );

  @override
  Future<void> crateApiMatrixMatrixServiceSendMessage({
    required MatrixService that,
    required String roomId,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixMatrixServiceSendMessageConstMeta,
        argValues: [that, roomId, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceSendMessageConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_send_message",
        argNames: ["that", "roomId", "body"],
      );

  @override
  Stream<List<MatrixChatMessage>> crateApiMatrixMatrixServiceWatchMessages({
    required MatrixService that,
    required String roomId,
  }) {
    final sink = RustStreamSink<List<MatrixChatMessage>>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
              that,
              serializer,
            );
            sse_encode_String(roomId, serializer);
            sse_encode_StreamSink_list_matrix_chat_message_Sse(
              sink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 16,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiMatrixMatrixServiceWatchMessagesConstMeta,
          argValues: [that, roomId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceWatchMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_watch_messages",
        argNames: ["that", "roomId", "sink"],
      );

  @override
  Stream<MatrixRoomsSnapshot> crateApiMatrixMatrixServiceWatchRooms({
    required MatrixService that,
  }) {
    final sink = RustStreamSink<MatrixRoomsSnapshot>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
              that,
              serializer,
            );
            sse_encode_StreamSink_matrix_rooms_snapshot_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 17,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiMatrixMatrixServiceWatchRoomsConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMatrixMatrixServiceWatchRoomsConstMeta =>
      const TaskConstMeta(
        debugName: "MatrixService_watch_rooms",
        argNames: ["that", "sink"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MatrixService => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MatrixService => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  MatrixService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MatrixServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MatrixService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MatrixServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MatrixService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MatrixServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<List<MatrixChatMessage>>
  dco_decode_StreamSink_list_matrix_chat_message_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<MatrixRoomsSnapshot>
  dco_decode_StreamSink_matrix_rooms_snapshot_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MatrixChatMessage> dco_decode_list_matrix_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_matrix_chat_message).toList();
  }

  @protected
  List<MatrixRoomSummary> dco_decode_list_matrix_room_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_matrix_room_summary).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MatrixChatMessage dco_decode_matrix_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MatrixChatMessage(
      eventId: dco_decode_String(arr[0]),
      roomId: dco_decode_String(arr[1]),
      senderId: dco_decode_String(arr[2]),
      body: dco_decode_String(arr[3]),
      timestampMs: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  MatrixRoomSummary dco_decode_matrix_room_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MatrixRoomSummary(
      roomId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      creatorId: dco_decode_opt_String(arr[2]),
      participantIds: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  MatrixRoomsSnapshot dco_decode_matrix_rooms_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MatrixRoomsSnapshot(
      rooms: dco_decode_list_matrix_room_summary(arr[0]),
      invitedRooms: dco_decode_list_matrix_room_summary(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  MatrixService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MatrixServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MatrixService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MatrixServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MatrixService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MatrixServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<List<MatrixChatMessage>>
  sse_decode_StreamSink_list_matrix_chat_message_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<MatrixRoomsSnapshot>
  sse_decode_StreamSink_matrix_rooms_snapshot_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MatrixChatMessage> sse_decode_list_matrix_chat_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MatrixChatMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_matrix_chat_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<MatrixRoomSummary> sse_decode_list_matrix_room_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MatrixRoomSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_matrix_room_summary(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MatrixChatMessage sse_decode_matrix_chat_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventId = sse_decode_String(deserializer);
    var var_roomId = sse_decode_String(deserializer);
    var var_senderId = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_timestampMs = sse_decode_i_64(deserializer);
    return MatrixChatMessage(
      eventId: var_eventId,
      roomId: var_roomId,
      senderId: var_senderId,
      body: var_body,
      timestampMs: var_timestampMs,
    );
  }

  @protected
  MatrixRoomSummary sse_decode_matrix_room_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_roomId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_creatorId = sse_decode_opt_String(deserializer);
    var var_participantIds = sse_decode_list_String(deserializer);
    return MatrixRoomSummary(
      roomId: var_roomId,
      name: var_name,
      creatorId: var_creatorId,
      participantIds: var_participantIds,
    );
  }

  @protected
  MatrixRoomsSnapshot sse_decode_matrix_rooms_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rooms = sse_decode_list_matrix_room_summary(deserializer);
    var var_invitedRooms = sse_decode_list_matrix_room_summary(deserializer);
    return MatrixRoomsSnapshot(
      rooms: var_rooms,
      invitedRooms: var_invitedRooms,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
    MatrixService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MatrixServiceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
    MatrixService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MatrixServiceImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixService(
    MatrixService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MatrixServiceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_matrix_chat_message_Sse(
    RustStreamSink<List<MatrixChatMessage>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_matrix_chat_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_matrix_rooms_snapshot_Sse(
    RustStreamSink<MatrixRoomsSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_matrix_rooms_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_matrix_chat_message(
    List<MatrixChatMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_matrix_chat_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_matrix_room_summary(
    List<MatrixRoomSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_matrix_room_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_matrix_chat_message(
    MatrixChatMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.eventId, serializer);
    sse_encode_String(self.roomId, serializer);
    sse_encode_String(self.senderId, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_i_64(self.timestampMs, serializer);
  }

  @protected
  void sse_encode_matrix_room_summary(
    MatrixRoomSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.roomId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.creatorId, serializer);
    sse_encode_list_String(self.participantIds, serializer);
  }

  @protected
  void sse_encode_matrix_rooms_snapshot(
    MatrixRoomsSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_matrix_room_summary(self.rooms, serializer);
    sse_encode_list_matrix_room_summary(self.invitedRooms, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class MatrixServiceImpl extends RustOpaque implements MatrixService {
  // Not to be used by end users
  MatrixServiceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MatrixServiceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_MatrixService,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_MatrixService,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_MatrixServicePtr,
  );

  Future<void> clearRooms() =>
      RustLib.instance.api.crateApiMatrixMatrixServiceClearRooms(that: this);

  Future<MatrixRoomSummary> createPrivateRoom({
    required String name,
    required List<String> invitedUserIds,
  }) => RustLib.instance.api.crateApiMatrixMatrixServiceCreatePrivateRoom(
    that: this,
    name: name,
    invitedUserIds: invitedUserIds,
  );

  Future<void> deleteRoom({required String roomId}) => RustLib.instance.api
      .crateApiMatrixMatrixServiceDeleteRoom(that: this, roomId: roomId);

  Future<String?> getDisplayName() => RustLib.instance.api
      .crateApiMatrixMatrixServiceGetDisplayName(that: this);

  Future<bool> isLoggedIn() =>
      RustLib.instance.api.crateApiMatrixMatrixServiceIsLoggedIn(that: this);

  Future<MatrixRoomSummary> joinInvitedRoom({required String roomId}) => RustLib
      .instance
      .api
      .crateApiMatrixMatrixServiceJoinInvitedRoom(that: this, roomId: roomId);

  Future<List<MatrixChatMessage>> listMessages({required String roomId}) =>
      RustLib.instance.api.crateApiMatrixMatrixServiceListMessages(
        that: this,
        roomId: roomId,
      );

  Future<MatrixRoomsSnapshot> listRooms() =>
      RustLib.instance.api.crateApiMatrixMatrixServiceListRooms(that: this);

  Future<String> login({
    required String username,
    required String password,
    String? deviceId,
  }) => RustLib.instance.api.crateApiMatrixMatrixServiceLogin(
    that: this,
    username: username,
    password: password,
    deviceId: deviceId,
  );

  Future<void> logout() =>
      RustLib.instance.api.crateApiMatrixMatrixServiceLogout(that: this);

  Future<String> registerUser({
    required String username,
    required String password,
    required String displayName,
  }) => RustLib.instance.api.crateApiMatrixMatrixServiceRegisterUser(
    that: this,
    username: username,
    password: password,
    displayName: displayName,
  );

  /// Descarta completamente o Client atual
  /// e cria outro.
  ///
  /// Isso é necessário quando uma sessão
  /// restaurada fica inválida, pois o Matrix SDK
  /// não permite substituir a autenticação de
  /// um Client que já teve sessão configurada.
  Future<void> resetClient() =>
      RustLib.instance.api.crateApiMatrixMatrixServiceResetClient(that: this);

  Future<void> restore({required String sessionJson}) => RustLib.instance.api
      .crateApiMatrixMatrixServiceRestore(that: this, sessionJson: sessionJson);

  Future<void> sendMessage({required String roomId, required String body}) =>
      RustLib.instance.api.crateApiMatrixMatrixServiceSendMessage(
        that: this,
        roomId: roomId,
        body: body,
      );

  Stream<List<MatrixChatMessage>> watchMessages({required String roomId}) =>
      RustLib.instance.api.crateApiMatrixMatrixServiceWatchMessages(
        that: this,
        roomId: roomId,
      );

  Stream<MatrixRoomsSnapshot> watchRooms() =>
      RustLib.instance.api.crateApiMatrixMatrixServiceWatchRooms(that: this);
}
