// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_private_room`, `get_display_name`, `is_logged_in`, `join_invited_room`, `list_rooms`, `login_password`, `logout`, `new`, `register_user`, `restore_session`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MatrixClient`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

class MatrixRoomSummary {
  final String roomId;
  final String name;

  const MatrixRoomSummary({required this.roomId, required this.name});

  @override
  int get hashCode => roomId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatrixRoomSummary &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          name == other.name;
}

class MatrixRoomsSnapshot {
  final List<MatrixRoomSummary> rooms;
  final List<MatrixRoomSummary> invitedRooms;

  const MatrixRoomsSnapshot({required this.rooms, required this.invitedRooms});

  @override
  int get hashCode => rooms.hashCode ^ invitedRooms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatrixRoomsSnapshot &&
          runtimeType == other.runtimeType &&
          rooms == other.rooms &&
          invitedRooms == other.invitedRooms;
}
