// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear_rooms`, `create_private_room`, `delete_room`, `get_display_name`, `is_logged_in`, `join_invited_room`, `list_rooms`, `login_password`, `logout`, `new`, `register_user`, `remove_room`, `restore_session`, `room_summary`, `rooms_snapshot`, `watch_rooms`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MatrixClient`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

class MatrixRoomSummary {
  final String roomId;
  final String name;
  final String? creatorId;
  final List<String> participantIds;

  const MatrixRoomSummary({
    required this.roomId,
    required this.name,
    this.creatorId,
    required this.participantIds,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      name.hashCode ^
      creatorId.hashCode ^
      participantIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatrixRoomSummary &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          name == other.name &&
          creatorId == other.creatorId &&
          participantIds == other.participantIds;
}

class MatrixRoomsSnapshot {
  final List<MatrixRoomSummary> rooms;
  final List<MatrixRoomSummary> invitedRooms;

  const MatrixRoomsSnapshot({required this.rooms, required this.invitedRooms});

  @override
  int get hashCode => rooms.hashCode ^ invitedRooms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatrixRoomsSnapshot &&
          runtimeType == other.runtimeType &&
          rooms == other.rooms &&
          invitedRooms == other.invitedRooms;
}
