// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MatrixService>>
abstract class MatrixService implements RustOpaqueInterface {
  static Future<MatrixService> create({
    required String homeserver,
    required String storePath,
    required String storePassphrase,
  }) => RustLib.instance.api.crateApiMatrixMatrixServiceCreate(
    homeserver: homeserver,
    storePath: storePath,
    storePassphrase: storePassphrase,
  );

  Future<String?> getDisplayName();

  Future<bool> isLoggedIn();

  Future<String> login({required String username, required String password});

  Future<void> logout();

  Future<String> registerUser({
    required String username,
    required String password,
    required String displayName,
  });

  Future<void> restore({required String sessionJson});
}
