// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_client`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MatrixService>>
abstract class MatrixService implements RustOpaqueInterface {
  Future<void> clearRooms();

  static Future<MatrixService> create({
    required String homeserver,
    required String storePath,
    required String storePassphrase,
  }) => RustLib.instance.api.crateApiMatrixMatrixServiceCreate(
    homeserver: homeserver,
    storePath: storePath,
    storePassphrase: storePassphrase,
  );

  Future<MatrixRoomSummary> createPrivateRoom({
    required String name,
    required List<String> invitedUserIds,
  });

  Future<void> deleteRoom({required String roomId});

  Future<String?> getDisplayName();

  Future<bool> isLoggedIn();

  Future<MatrixRoomSummary> joinInvitedRoom({required String roomId});

  Future<MatrixRoomsSnapshot> listRooms();

  Future<String> login({
    required String username,
    required String password,
    String? deviceId,
  });

  Future<void> logout();

  Future<String> registerUser({
    required String username,
    required String password,
    required String displayName,
  });

  /// Descarta completamente o Client atual e cria outro.
  ///
  /// Isso é necessário quando uma sessão restaurada fica inválida,
  /// pois o Matrix SDK não permite substituir a autenticação de um
  /// Client que já teve uma sessão configurada.
  Future<void> resetClient();

  Future<void> restore({required String sessionJson});

  Stream<MatrixRoomsSnapshot> watchRooms();
}
